---

- hosts: piratar1
  vars:
    telegraf_hostname: pir1
  pre_tasks:
  - name: Install programs
    apt: pkg={{ item }} state=installed update_cache=true cache_valid_time=3600
    with_items:
      - curl
      - htop
      - python-pip
      - python3-pip

  roles:
    - docker
    - telegraf
    - grafana-influx-docker

  tasks:
  - name: Create our working docker user
    user:
      name: "{{working_user}}"
      shell: /bin/bash
      generate_ssh_key: yes
      group: docker
